### ISSUE TITLE
LGPL license violation

### ISSUE THREAD

**Issue by jamesbt365** [archev727/OpenParbloDriver#1]
OpenTabletDriver comes with the LGPL license, which requires that the source-code be redistributed along with the binary distribution. Unfortunately, you are not following the terms of the license.

You are in violation of the legal software license that OpenTabletDriver was licensed under, please amend this or take the project down.

**Comment by archev727** [comment]
Sorry, I completely forgot

**Comment by archev727** [comment]
> OpenTabletDriver comes with the LGPL license, which requires that the source-code be redistributed along with the binary distribution. Unfortunately, you are not following the terms of the license.
> 
> You are in violation of the legal software license that OpenTabletDriver was licensed under, please amend this or take the project down.

Just a quick question. Do I need to add all the OTD source code or should I just add the files that I modified or added?

**Comment by Kuuuube** [comment]
The entirety of the source code that you are using to build the binaries under github releases.

**Comment by archev727** [comment]
Ready! Thank you very much for your help <3 

Next time I won't make such mistakes
